language: c
script: asdf plugin-test gradle https://github.com/ypconstante/asdf-gradle.git 'gradle -v'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
